# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wordlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 727)
        Form.setStyleSheet("#Form{\n"
"border-image: url(:/resimler/hacker.jpg);\n"
"}\n"
"#page_3{\n"
"border-image: url(:/resimler/hacker.jpg);\n"
"}\n"
"#page_4{\n"
"border-image: url(:/resimler/hacker.jpg);\n"
"}\n"
"#pushButton{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"#lineEdit{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"#pushButton_2{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"#lineEdit_2{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"#radioButton{\n"
"color:rgb(12, 240, 67);\n"
"}\n"
"#radioButton_2{\n"
"color:rgb(12, 240, 67);\n"
"}\n"
"#radioButton_3{\n"
"color:rgb(12, 240, 67);\n"
"}\n"
"#radioButton_4{\n"
"color:rgb(12, 240, 67);\n"
"}\n"
"")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 9, 729, 709))
        self.stackedWidget.setStyleSheet("#lineEdit_3{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"#lineEdit_4{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"#spinBox_3{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"#spinBox_4{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(197, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 9, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(197, 164, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 10, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 9, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setCheckable(True)
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_2.addWidget(self.radioButton_4, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(117, 51, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 66, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(12, 240, 67);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_5 = QtWidgets.QRadioButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("color:rgb(12, 240, 67);")
        self.radioButton_5.setCheckable(True)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_6.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("color:rgb(12, 240, 67);")
        self.radioButton_6.setCheckable(True)
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_6.addWidget(self.radioButton_6)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 5, 1, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(12, 240, 67)")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox_3 = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(12, 240, 67)")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinBox_4 = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)
        self.gridLayout_2.addLayout(self.formLayout_2, 7, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.radioButton_7 = QtWidgets.QRadioButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("color:rgb(12, 240, 67);")
        self.radioButton_7.setCheckable(True)
        self.radioButton_7.setChecked(False)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_8.addWidget(self.radioButton_7)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 4, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(12, 240, 67)")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 8, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 10, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2.addLayout(self.verticalLayout_7, 5, 2, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2.addLayout(self.verticalLayout_9, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.page_3)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color:rgba(0, 0, 0,0.5);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"DejaVu Sans\";\n"
"    border-color: rgb(0, 0, 127);\n"
"    border-radius:4px;\n"
"    border:2px solid rgb(12, 240, 67);}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(12, 240, 67);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Şifre Kayıt"))
        self.radioButton_4.setText(_translate("Form", "Özel Karakter"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Kaç adet şifre :</span></p></body></html>"))
        self.radioButton_5.setText(_translate("Form", "Küçük Harf"))
        self.radioButton_6.setText(_translate("Form", "Sayılar"))
        self.label_5.setText(_translate("Form", "Max"))
        self.label_6.setText(_translate("Form", "Min"))
        self.radioButton_7.setText(_translate("Form", "Büyük Harf"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Kayıt edilecek klasör yolu </span></p></body></html>"))
        self.label.setText(_translate("Form", "World List"))
import resimler_rc
